apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: go-helloworld-2
  name: go-helloworld-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-helloworld-2
  template:
    metadata:
      labels:
        app: go-helloworld-2
    spec:
      containers:
      - image: ghcr.io/2022-4400-exp/4436-go-helloworld-2:24e3b1f379b6cd621b84641a865a3fe859a7a0ee@sha256:925b07f319d9dc0873b3ee75111b780c22ea21c211e2b175476959fdbedfcaa5
        name: go-helloworld-2